# Generated by Django 3.0.4 on 2020-03-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('origin_city', models.CharField(max_length=200)),
                ('origin_state', models.CharField(max_length=2)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_city', models.CharField(max_length=200)),
                ('destination_state', models.CharField(max_length=2)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
